[package]
name = "mdevctl"
version = "0.1.0"
authors = ["Jonathon Jongsma <jjongsma@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
env_logger = "0.8.3"
log = "0.4"
serde_json = {version = "1.0", features = ["preserve_order"]}
structopt = "0.3.13"
uuid = {version = "0.8.2", features = ["v4"]}
faccess = "0.2.3"
